### ISSUE TITLE
Problem: dashboard configuration is set in Dockerfile

### ISSUE THREAD

**Issue by scollazo** [artefactual-sdps/enduro#608]
**Describe the bug**

Dashboard container includes [configuration values 
](https://github.com/artefactual-sdps/enduro/blob/main/dashboard/Dockerfile#L4)

**To Reproduce**

- Build dashboard container
- Pass variables pointing to a different dex auth server

**Expected behavior**

Dex auth can be configured at runtime, avoiding the need of rebuilding the container for each environment.

**Screenshots**

**Additional context**

**Comment by jraddaoui** [comment]
We could use Nginx to pass those configuration values with environment variables: https://developers.redhat.com/blog/2021/03/04/making-environment-variables-accessible-in-front-end-containers#.

**Comment by djjuhasz** [comment]
@jraddaoui the Vite OIDC environment variables are set in the dashboard kube config: 
https://github.com/artefactual-sdps/enduro/blob/main/hack/kube/base/enduro-dashboard.yaml

My local dev environment works fine after simply removing the OIDC environment variables from the Dockerfile:
https://github.com/artefactual-sdps/enduro/pull/646/commits/9437020ee23c4231f467caf4d06e6756471740b1

Do you think it is necessary to set the OIDC environment variables in other contexts, or do you think the commit above is sufficient?

**Comment by jraddaoui** [comment]
Hi @djjuhasz, welcome back!

In [development](https://github.com/artefactual-sdps/enduro/blob/main/Tiltfile#L20) we use the [builder](https://github.com/artefactual-sdps/enduro/blob/main/dashboard/Dockerfile#L3) target from that Dockerfile. That target builds the assets for the final Nginx based image but it also runs Vite's dev server. The dev server is able to read those variables from the environment and pass it to the frontend, it also works with [.env files](https://vitejs.dev/guide/env-and-mode.html#env-files) where we have [the same defaults](https://github.com/artefactual-sdps/enduro/blob/main/dashboard/.env).

However, for production we build the final assets and serve them with Nginx and, with the current implementation, those env vars need to be set at build time, so having them in a k8s manifest has no effect. What I linked above explains a way to pass those env vars with Nginx to the frontend assets after build, which then will allow to configure them in the k8s manifest using the same Docker image and frontend assets.

**Comment by djjuhasz** [comment]
@jraddaoui I've invested most of the day trying to figure out how the dashboard runs in dev vs. prod and how the Nginx ENV setting script works.  I'm a little cross-eyed from the mental effort, but I *think* I mostly understand now. ;)

To restate what you said above and confirm my understanding, I think what's happening in the `dashboard/Dockerfile` is:
- In dev, the dashboard Docker container is started using the default `CMD npm run dev` directive, which starts the Vite dev server on port 3000, which is exposed to localhost
- In prod, the dashboard Docker container is started with `docker run nginx -g 'daemon off;'` (or something similar) which starts nginx server on port 80, which is exposed to the WAN

In the prod (nginx) case, the client app is built with Vite in the builder image, then the distribution files are copied to the nginx image.  For some reason (I'm not clear on why), the Dex/OIDC info needs to present for the Vite build step.

---

Now to the script: https://developers.redhat.com/blog/2021/03/04/making-environment-variables-accessible-in-front-end-containers#

You say "We could use Nginx to pass those configuration values with environment variables", but I don't think that is an accurate description of what the script does.   My understanding of the script is that runs a Bash script that rewrites the variables in a "config.json" file that is read by Vue.js (or whatever JS framework is being used), then starts Nginx.  Nginx isn't actually setting or passing any ENV vars.  I think the only reason the script uses ENV vars at all is because they can be set at runtime rather than at build time.

However it seems to me that if the script requires Vue.js to read config variables at run time from a "config.json" file, then it might be possible (and easier) to read the config from ENV vars directly instead?

**Comment by jraddaoui** [comment]
> In the prod (nginx) case, the client app is built with Vite in the builder image, then the distribution files are copied to the nginx image. For some reason (I'm not clear on why), the Dex/OIDC info needs to present for the Vite build step.

The Vite build step reads those env vars and adds them to the distribution files.

> I think the only reason the script uses ENV vars at all is because they can be set at runtime rather than at build time.

That's what we need too, so we can use the same image and distribution files with different configuration values.

> However it seems to me that if the script requires Vue.js to read config variables at run time from a "config.json" file, then it might be possible (and easier) to read the config from ENV vars directly instead?

It may not be exact solution we implement, but it shows a way to modify the final assets to be able to read those config values at runtime.

**Comment by djjuhasz** [comment]
@jraddaoui I was thinking about this while making dinner, and I think the script is actually replacing the variables with the ENV var value in the *distribution* files, not in the config file. :exploding_head:  I think we could do a simpler search and replace on the default OIDC values. :)

**Comment by jraddaoui** [comment]
That would work @djjuhasz. You could also create and track an `.env.production` file as follows:

```
VITE_OIDC_AUTHORITY=$VITE_OIDC_AUTHORITY
VITE_OIDC_CLIENT_ID=$VITE_OIDC_CLIENT_ID
VITE_OIDC_REDIRECT_URI=$VITE_OIDC_REDIRECT_URI
VITE_OIDC_AUDIENCE_CLIENT_ID=$VITE_OIDC_AUDIENCE_CLIENT_ID
```

I believe the build process will use that file while the dev server will keep using the `.env` file. This may simplify the search and replace operation and will avoid issues if we change those defaults in the future.

**Comment by djjuhasz** [comment]
Fixed by https://github.com/artefactual-sdps/enduro/commit/017484e3bb13e75453e0ae41be1891ee3403119e
